### ISSUE TITLE
Consider how to support single record data

### ISSUE THREAD

**Issue by paulspiteri** [msolvaag/redux-db#10]
Currently the only way to access "single record" data is to model it as a table or put it in regular redux, outside of the db. 
The problem with putting it outside of the db is that the db-reducers don't receive the redux state. Perhaps that would be the simple solution.

Thanks again, really great project.

**Comment by msolvaag** [comment]
Well supporting single record data kind of breaks the database idea. One way to do this is to nest the reducer state in a different way.

````typescript
import { dbInstance } from "../schema";

const dbReducer = (state = {}, action: Action, aside: any) => {
    const session = dbInstance.createSession(state) as Session;

    switch (action.type) {
        case "SOME_ACTION":
            // ...
            break;
    }

    return session.commit();
};

const asideReducer = (state = {}, action: Action) => {
    switch (action.type) {
        case "SOME_ACTION":
            return { ...state, ...newState };
        default:
            return state;
    }
};

export const reducer = (state = { db: {}, aside: {} }, action: Action) => {
    return {
        aside: asideReducer(state.aside, action),
        db: dbReducer(state.db, action, state.aside)
    };
};

```

**Comment by msolvaag** [comment]
You might want to change the "root" reducer to bring along the latest "aside" state to the db reducer.

``` typescript
export const reducer = (state = { db: {}, aside: {} }, action: Action) => {
    const aside = asideReducer(state.aside, action);
    return {
        aside: aside,
        db: dbReducer(state.db, action, aside)
    };
};
```

**Comment by paulspiteri** [comment]
Yeah the only problem with this is it means we cant use your combineReducers / Reducer interface.
I was suggesting adding the ApplicationState to that interface as a 3rd parameter, but if you think that's inappropriate, fair enough, we can write it like this.
thanks

**Comment by msolvaag** [comment]
I'ts no problem to add a third param to the Reducer interface.
To make use of the combineReducers session wrapping, I'm proposing a construct like:

``` typescript
export const reducer = (state = { db: {}, aside: {} }, action: Action) => {
    const aside = asideReducer(state.aside, action);
    return {
        aside: aside,
        db: dbInstance.reduce( state.db, action, [ dbReducer1, dbReducer2 ], aside )
    };
};

const dbReducer1: Reducer = ( session: Session, action: Action, state: AppState ) => { ... }
```

**Comment by paulspiteri** [comment]
If you don't mind making that change, it'd be great.
thanks

**Comment by msolvaag** [comment]
Added the reduce method in v0.7.6
```
reduce(state: any, action: any, reducers: Reducer | Reducer[], arg?: any)
```

**Comment by msolvaag** [comment]
Safe to close?

**Comment by paulspiteri** [comment]
Yep, got it working
Thanks!!

**Comment by keenondrums** [comment]
Guys, why would you make the API more complex? Maybe I'm missing something but can't it be something like that?

```
import { dbInstance } from "./schema";
import { combineReducers } from "redux";

const db = dbInstance.combineReducers((session, action) => {
    // Do your stuff with the session
});

const aside = (state, action: Action) => {
   // DO whatever you want with this aside state
};

export default combineReducers({
  aside,
  db
})
```

**Comment by msolvaag** [comment]
Well, this was for the case when you want to pass along different parts of the state tree. 

combineReducers does not pass along the whole state to each individual reducer.

**Comment by keenondrums** [comment]
Oh, I see. Thnx! Considering that db.combineReducers is just a decorator, could we do something like this?
```
import { dbInstance } from "./schema";

const dbReducer = (state) => (session, action) => {    
    const { MyTable } = session.tables as Session;

    switch (action.type) {
        case "SOME_ACTION":
            // ...
            break;
    }
};

const asideReducer = (state = {}, action: Action) => {
    switch (action.type) {
        case "SOME_ACTION":
            return { ...state, ...newState };
        default:
            return state;
    }
};

export const reducer = (state = { db: {}, aside: {} }, action: Action) => ({
    aside: asideReducer(state.aside, action),
    db: dbInstance.combineReducers(dbReducer(state))
});
```
@msolvaag would you consider renaming your combineReducers to something like withSession? combineReducers name is kind of confusing from my point of view. After all it's just a simple decorator which handles your session for you.

**Comment by msolvaag** [comment]
Well, the combineReducers function is accepting one or more "db" reducers wrapped in the session context.  
```
combineReducers = ( ...reducers:Reducer[] ) => dbReducer
```

So It is combining reducers..   But I could see it may be confusing with redux.combineReducers.  

But, I think you may have misunderstood the issue some. This is a special case  and I think most people would not go this way.  Using the redux.combineReducers is  still the preferable choice.
http://redux-db.readthedocs.io/en/latest/guide/store.html

Doing the way you suggested, would still require the dbInstance.combineReducers to get the db branch and the action.
So you would end up with basically the same as the "reduce" method.

```
export const reducer = (state = { db: {}, aside: {} }, action: Action) => ({
    aside: asideReducer(state.aside, action),
    db: dbInstance.reduce(state.db, action, dbReducer(state))
/// or
    db: dbInstance.reduce(state.db, action, dbReducer, state)
});
```

**Comment by keenondrums** [comment]
Alright. I just wanted to express my concern about extending API to cover a corner case which is not even considered normal

**Comment by msolvaag** [comment]
ah, I see. Sure. I agree, less is more. It may be changed before v1.0
