### ISSUE TITLE
Comparison to redux-orm

### ISSUE THREAD

**Issue by keenondrums** [msolvaag/redux-db#13]
Hi! Could you elaborate a bit on the reasoning behind creating this lib? How is it different to redux-orm? What would be a use case when one chooses this lib over redux-orm?

**Comment by msolvaag** [comment]
Sure thing.   The main reason was I found the redux-orm to be a bit bloated and lacking some functionallty. 

The main differences:
- redux-db includes a normalization step during insert/update ops
- schema is defined by a json object
- supports cascading deletes
- no dependencies

So by using redux-db you do not have to pre-normalize your data ( by eg. normalizr ).
An upsert to a Table with unormalized data will normalize it and apply updates throughout the schema.

**Comment by keenondrums** [comment]
@msolvaag Do you have a road map? Don't get me wrong, you did a tremendous amount of work here. Respect! But for me, personally, lack of tests is a significant downside.

**Comment by msolvaag** [comment]
Thanks.  There are a few tests handling the basic operations, but I agree there should be a lot more!

My plans pushing for 1.0.0:
- Optimization for large data sets
- Improved constraint checks
- Write a lot of tests :)

Feel free to add suggestions!

**Comment by Martaver** [comment]
As feedback, I'm using this library in a Typescript project without any strange bugs or foibles. Minimal fuss, fairly flexible.
