### ISSUE TITLE
FK reference properties in TableRecords return values of type 'any'.

### ISSUE THREAD

**Issue by Martaver** [msolvaag/redux-db#14]
All my one-to-many FK reference properties seem to return the value's type as any[]. Take this for example:

Where my schema is set up as:
```
interface IThingRecord extends TableRecord<IThing> {
    linksFrom: TableRecordSet<ILinkRecord>;
    linksTo: TableRecordSet<ILinkRecord>;
    properties: TableRecordSet<IPropertyRecord>;
}

interface ILinkRecord extends TableRecord<ILink> {
    fromThing: IThingRecord;
    toThing: IThingRecord;
}

export type ThingTable = Table<IThing, IThingRecord>;
export type LinkTable = Table<ILink, ILinkRecord>;
export interface ISession extends TableMap {
    Thing: ThingTable;
    Link: LinkTable;
}

export const db = createDatabase({
    Thing: {
        id: { type: 'PK' },
    },
    Link: {
        id: { type: 'PK' },
        fromThingId: { propName: 'fromThing', references: 'Thing', relationName: 'linksFrom' },
        toThingId: { propName: 'toThing', references: 'Thing', relationName: 'linksTo' },
    },
});
```
_(IThing & ILink are just id, name and description)_

Then I do:
```
db.selectTables<ISession>(state.schema.current).Thing.get(1).linksTo.value
```
And when I try to get links that belong to my 'thing', the return type of value is `any[]`.

The linksTo property is `TableRecordSet<ILinkRecord, any>` where it should be `TableRecordSet<ILinkRecord, ILink>`.

Non-array FK properties are fine. e.g. 
```
db.selectTables<ISession>(state.schema.current).Link.get(1).fromThing.value
```

**Comment by msolvaag** [comment]
Hi

I'll make the change.  Thanks for the feedback!

**Comment by msolvaag** [comment]
A bit ahead of my self there.  It's kinda stupid, but to know what your data model type is, you need to define it. 

So you need to do:
```
interface IThingRecord extends TableRecord<IThing> {
    linksFrom: TableRecordSet<ILinkRecord, ILink>;
    linksTo: TableRecordSet<ILinkRecord, ILink>;
    properties: TableRecordSet<IPropertyRecord, IProperty>;
}
```

**Comment by Martaver** [comment]
Ah, of course...

Is there any scenario where you wouldn't want to specify types here? 

I would imagine that removing the defaults on the type arguments might be a good idea, to prevent developer errors when defining their schema.

Thanks for the quick reply :)
