### ISSUE TITLE
Best hook to generate uids for missing PKs?

### ISSUE THREAD

**Issue by Martaver** [msolvaag/redux-db#15]
On upserts, it would be nice to have PKs generated for new records, whenever they're missing. A simple uid would suffice.

I do this currently with a custom ModelFactory/TableModel that overrides upsert and injects the PK if missing, but this still fails if I try to upsert any denormalized data -> the normalization process also requires PKs no nested entities.

If we assume that any record without a PK, should simply have a uid created for it, how could we achieve this in redux-db?

**Comment by msolvaag** [comment]
Hi, I will look into this.

**Comment by Martaver** [comment]
I'd imagine a simple 'missing PK' hook could be added, passing some context information to the callback.
If the callback doesn't exist or returns undefined, then continue on to the standard error now.

This leaves open the implementation, allowing support for generating any kind of ID, client or server side.

**Comment by msolvaag** [comment]
So I've pushed an update including this hook.   You may now define a general onMissingPk hook when creating the db.

```
createDatabase( 
 { schemaDef..}, 
 {
  onMissingPk: ( record: any,  schema: TableSchema ) => string
 } 
);
```

**Comment by Martaver** [comment]
This is mostly working...

I've found an issue with redux-db not setting the 'id' property on the models it generates a missing PK for.

This causes problems down the line when using functions like 'update', where a Partial<IModel> is expected, but id is missing.

**Comment by msolvaag** [comment]
Okey, I'll try to correct this as soon as possible.

**Comment by Martaver** [comment]
Rolled my own fix... this doesn't handle compound PKs... not sure of the best approach for that. But if the PK is single, it'll also set the model's PK.

https://github.com/msolvaag/redux-db/pull/17

**Comment by msolvaag** [comment]
So after the PR merge ( npm v0.9.10 )  I've made some changes to ensure that pure updates does not use this hook.  Pushed a new update  v0.9.11.
