### ISSUE TITLE
Re-think relationship with redux

### ISSUE THREAD

**Issue by Martaver** [msolvaag/redux-db#16]
I think it's interesting that redux-db and redux-orm include the word 'redux' in their name, when they're quite decoupled from it. They just handle work with normalized data structures in an immutable way.

Their goal is extremely valuable, and useful in many scenarios. In my mind, something generic like 'object-db' and a clean break from redux would make sense.

What are your thoughts?

**Comment by msolvaag** [comment]
Funny that you mention it. Coming from a redux stack. I felt it like an extension to redux, but in later projects I've been using Vue/vuex. So my next step with redux-db would be to make it more standalone. I might move the project to a new named repo.

Thanks for all the great feedback.
