### ISSUE TITLE
Upsert should accept IModelRecord properties too not just IModel

### ISSUE THREAD

**Issue by Martaver** [msolvaag/redux-db#18]
In typescript, we will get an error if we try to upsert an object literal that includes more properties than IModel.

e.g.

```
const bankAccount = Thing.upsert({
        name: 'Bank Account',
        description: 'Your personal bank account.',
        properties: [
            {
                name: 'IBAN',
                description: 'International Bank Account Number',
            },
            { name: 'Balance', description: 'The current balance' },
        ],
    });
```

In this, `properties` is a problem, since it doesn't exist on the model type IThing - it's a FK relation declared on IThingRecord, instead.

But, in order to take advantage of the normalizing features, I want to upsert properties under the bank account in a denormalized way.

I wonder if Upsert accepted the record type merged with the model type, whether we could work with the denormalized data in a type safe way?

**Comment by msolvaag** [comment]
true, this makes sense.  I'll look into it soon.

**Comment by msolvaag** [comment]
This is fixed in upcoming version
