### ISSUE TITLE
TableModel.values is undefined

### ISSUE THREAD

**Issue by martinemmert** [msolvaag/redux-db#19]
Hi there, just want to note that the getter property `values` on the `TableModel` is undefined and non existend in the code.

The documentation says something different:
http://redux-db.readthedocs.io/en/latest/models.html#tablemodel

I can work around that by using the ClassFactory.

Keep up the great work!

**Comment by msolvaag** [comment]
Hi
This property was renamed to the method getValues(). Docs updated soon.
Thanks for the feedback.
