### ISSUE TITLE
Id merge operation violates unique constraint for id

### ISSUE THREAD

**Issue by ZnarKhalil** [msolvaag/redux-db#20]
I am using redux-db with react-native, I have a Configuration Table so, when the app runs for the first time i need to initialize the Configuration table with some values, to achieve that i tried to insert the values in my default reducer case .
`default:
            Configuration.insert({
                phone: "1",
                confirmResult: '',
                loggedIn:false
            });
            return  session.commit();`
but when the app start it's showing an error **Id merge operation violates unique constraint for id: "1"**
what is the problem?
and is there a better solution to initialize a table.

**Comment by msolvaag** [comment]
Hi there.  Generally you would put the "non db" stuff outside the db root.  Then using a regular reducer with initial state.

**Comment by msolvaag** [comment]
But.. If you still wish to have a configuration table. Then you should handle that using a app init action. NOT in the default case. The default case will be triggered each action fired not matched by your switch, causing your error.

**Comment by msolvaag** [comment]
```
// import db instance
import { db } from './schema';

export default db.combineReducers((tables, action) => {
    const { Configuration } = tables;

    switch (action.type) {
        case 'APP_INIT':
            Configuration.insert({ phone: "1", confirmResult: '', loggedIn: false });
    }
});


// then somewhere after store init
store.dispatch({ type: 'APP_INIT' });
```

**Comment by ZnarKhalil** [comment]
Thank you, it's working fine now and i changed the initialization of config table from default case to app init case and that was great.
