### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by paulspiteri** [msolvaag/redux-db#7]
Hi
Is there a reason why the types such as TableRecord have the value as any? Surely this should be a < T > ?

Also, it seems like one-to-one table relationships aren't really supported - is that right?

Otherwise, great project!

**Comment by msolvaag** [comment]
Thanks for the feedback. I know there are some issues with the typings. And I haven't mentioned it much in the documentation either.  I will try to improve this in the next update.

As for one 2 one relationship. Not implemented yet. 
I will open a ticket.

**Comment by msolvaag** [comment]
Just had a quick glance at the code. Where exactly does the TableRecord have the value any?

**Comment by paulspiteri** [comment]
Hi, yeah that's what I meant. Ideally we could specify it, TableRecord<T>

**Comment by msolvaag** [comment]
So I've done some work.  Added the missing <T> for TableRecord and support for one to  one relationships. And even completed the "on delete cascade" feature.  

To specify that a FK is a one 2 one relation you add the "unique":true flag in the field def.  Like so:

```javascript
{
 ...
 "postID": { type: "FK", references: "Post", relationName: "uniqueObject", unique: true }
}
```

**Comment by paulspiteri** [comment]
That was fast! The typings are much better now, but I think there's a small problem with them still.

If the T in  TableRecord<T> should be the actual data type (E.g. Customer)
then what is the T in TableRecordSet<T> ?
Should it be the TableRecord type or the data type (Customer)?

If it should be the TableRecord type, then there's a problem with the map function.

**Comment by paulspiteri** [comment]
I think you've intended it to be the data type in TableRecordSet.
I think it'd be better if it had the TableRecord type too, so that map would give you the correct record without a cast.

**Comment by msolvaag** [comment]
It may be confusing but, my intention is this: 

T = RecordModel<V>
V = Your data model

This approach gives the possibility to define the session interface. Like so:
``` typescript
import * as ReduxDB from "redux-db";

// Data models
export interface Project{
    id: number,
    title: string;
}
export interface Task{
   id: number;
   projectId: number;
}

// Schema models
export interface ProjectRecord extends ReduxDB.Record<Project> {
    tasks: ReduxDB.RecordSet<TaskRecord>;
}

export interface TaskRecord extends ReduxDB.Record<Task> {
    project: ProjectRecord;
}

export interface Session {
    Project: ReduxDB.Table<ProjectRecord>;
    Task: ReduxDB.Table<TaskRecord>;
}

// Reducer
export const dbReducer = (session: Session, action: Action) => {
    const { Project, Task } = session;

    switch (action.type) {
        case "SOME_ACTION":{
            const project = Project.get(action.payload);
            // project.tasks === typeof RecordSet<TaskRecord>
            // project.tasks.map( t=> t.value === typeof Task )
            break;
        }
    }
}
```
Since the schema definition is a JSON object we can not infer the typings. We need to define the types with relations.  This is a drawback using a JSON schema, but I think the advantages is greater.

Make sense?

**Comment by paulspiteri** [comment]
Thanks for that example it cleared up a lot. Fixed all the casts now!
Also btw, the cascade delete appears to work.

**Comment by paulspiteri** [comment]
The only other issue I have at the moment, I've commented on in #8 
I'm not sure if you'll see that as it's a closed issue already.

Thanks for the quick turn around on the typings
