### ISSUE TITLE
Add support for one 2 one relationships

### ISSUE THREAD

**Issue by msolvaag** [msolvaag/redux-db#8]
Current implementation assumes one to many relationships when defining a foreign key.

**Comment by msolvaag** [comment]
To specify that a FK is a one 2 one relation you add the "unique" flag in the field def. Like so:

"SomeTable": {
 ...
 "postID": { type: "FK", propName: "post", references: "Post", relationName: "uniqueObject", unique: true }
}
This will produce a "post.uniqueObject" and a "someTable.post" property. It will also enforce the unique constraint when updating/inserting.

Note. These features is found in the 0.6.0 version.

**Comment by paulspiteri** [comment]
This works nicely in that I now get a Record instead of a RecordSet

However without being able to assign a reference/relationship on a PK field it doesn't really solve the problem fully.

I can give an example if you'd like

**Comment by msolvaag** [comment]
If you could, then it would be great.

**Comment by msolvaag** [comment]
ah, I think I understand.  You want:
```
"id": { type: "PK", references: "SomeTable",  relationName: "otherTable", unique: true }
```

Giving a "someTable.otherTable" property.

**Comment by paulspiteri** [comment]
yes, i think the code currently only looks for FK fields.
I had to hack around it by adding "id2" field :)

**Comment by msolvaag** [comment]
Yes, only FK at the moment.  I'll add support for PK's later today.

**Comment by msolvaag** [comment]
So.. I've included support for PK's having the "references" definition.  One important thing;  IF the name of the field is "id", then you need to include the "propName" in the field definition.  Since "id" is already a reserved property on the model.

 ```
"id": { type: "PK", propName: "someTable", references: "SomeTable",  relationName: "otherTable", unique: true }
```
Since a PK may also define a FK, then I choose to remove the field type "FK".  This is implied by the usage of "references".  This is a breaking change, so i bumped the minor version to 0.7.0.

Thanks for the great feedback!

**Comment by msolvaag** [comment]
just applied a patch. so the latest version is 0.7.1

**Comment by paulspiteri** [comment]
It works absolutely great. Thanks!

**Comment by paulspiteri** [comment]
There's one small problem with this.
If I want cascade deletes to work, I need to define the relationship on the child table, rather than on the join-table. Ideally I could define the 1-1 relationship on the other side (the join-table side) and cascade to still work.

Alternatively, being able to define multiple relationships from the same field would be a solution. 

Without one of these approaches, it's impossible to have 2 different parent tables relate to a child table with their respective cascade deletes working.

**Comment by paulspiteri** [comment]
I think you can ignore this last comment for now. The simple solution will be to extend the join table with more columns.
Feel free to close this issue now, thanks!

**Comment by msolvaag** [comment]
If I'm understanding you correctly. You have something like this?
``` javascript
{
    "Parent1": {
        "id": { "type": "PK" }
    },

    "Parent2": {
        "id": { "type": "PK" }
    },

    "Parent1Child":{
        "parentId": { "type": "PK", "references": "Parent1", "relationName": "children", "cascade": true },
        "childId": { "type": "PK", "references": "Child", "relationName": "parents1", "cascade": true }
    },

    "Parent2Child":{
        "parentId": { "type": "PK", "references": "Parent2", "relationName": "children", "cascade": true },
        "childId": { "type": "PK", "references": "Child", "relationName": "parents2", "cascade": true }
    },

    "Child": {
        "id": { "type": "PK" }
    }
}
```

**Comment by msolvaag** [comment]
Okey, I'm closing this now.
